backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\user;
use backend\models\Staff;
use backend\models\change;
use backend\models\SearchUser;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for user model.
 */
class UserController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all user models.
     * @return mixed
     */
    public function actionIndex() {
        $this->redirect(['/']);
    }

    public function actionListUsers() {
        $searchModel = new SearchUser(['type' => 'user']);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionListStaff() {
        $searchModel = new SearchUser(['type' => 'staff']);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('list_staff', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionChangepassword($id = 'null') {

        if ($id == 'null') {
            $id = Yii::$app->user->identity->id;
        } else {
            $id = $id;
        }

        $model = new change();

        if ($model->load(Yii::$app->request->post())) {
            $models = change::findOne($id);
            $oldpass = $models->password;
            //echo "<pre>"; print_r($oldpass);die;
            $pass = Yii::$app->request->post();
            $new_pass = md5($pass['change']['password']);
            //  echo "<pre>"; print_r($pass['change']['password']);die;
            if ($new_pass == $oldpass) {
                $password = md5($pass['change']['newpassword']);
                $models->password = $password;
                $models->newpassword = '1';
                $models->con_password = '1';



                if ($models->save()) {
                    $old_pa = 'Password has been changed successfully';
                    Yii::$app->session->setFlash('old_pa', $old_pa);
                    return $this->goHome();
                } else {
                    print_r($models->getErrors());
                }
            } else {

                $old_pa = 'Your old password is wrong So please should be correct password';
                Yii::$app->session->setFlash('old_pa', $old_pa);
                return $this->redirect(['changepassword?id=' . $id]);
            }
        } else {


            return $this->render('changepassword', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Displays a single user model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new user model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreateUser() {
        $model = new user();
        if ($model->load(Yii::$app->request->post())) {
            $pass = Yii::$app->request->post();
            $passwo = $pass['user']['password'];
            $passw = md5($passwo);
            $model->password = $passw;
            $model->type = 'user';
            $status = $model->save();
            if ($status) {                
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::$app->session->setFlash('error', 'The user could not be saved. Please, try again.');
                return $this->render('create', ['model' => $model]);
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    public function actionCreateStaff() {
        $model = new Staff();

        if ($model->load(Yii::$app->request->post())) {
            $pass = Yii::$app->request->post();
            $passwo = $pass['Staff']['password'];
            $passw = md5($passwo);
            $model->password = $passw;
            $model->type = 'staff';
            $model->save();
            return $this->redirect(['list-staff', 'id' => $model->id]);
        } else {
            return $this->render('create-staff', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing user model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    public function actionUpdateStaff($id) {
        $model = Staff::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['list-staff', 'id' => $model->id]);
        } else {
            return $this->render('update-staff', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing user model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['list-users']);
    }

    /**
     * Finds the user model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return user the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = user::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use yii;
use yii\rest\ActiveController;
use frontend\models\User;
use frontend\models\EmailTemplate;
use yii\db\Connection;

class UserController extends ActiveController {

    public $modelClass = 'frontend\models\User';

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionGetalluser() {
        $response_array = array();
        $access_key = yii::$app->params['access_key'];
        $request_data = (object) $_POST;
        if (!isset($request_data)) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide input data!';
            return $response_array;
        } else if (!isset($request_data->access_key) || $request_data->access_key != $access_key) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Unauthorized Access !!';
            return $response_array;
        }

        $res = User::find()->select('id, username, email, phone_no, address, status, type')->all();
        $response_array['statusCode'] = 200;
        $response_array['status'] = 'success';
        $response_array['responseData']['message'] = 'success';
        $response_array['responseData']['data_array'] = $res;
        return $response_array;
    }

    public function actionGetuserbyid() {
        $response_array = array();
        $access_key = yii::$app->params['access_key'];
        $request_data = (object) $_POST;

        if (!isset($request_data)) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide input data!';
            return $response_array;
        } else if (!isset($request_data->access_key) || $request_data->access_key != $access_key) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Unauthorized Access !!';
            return $response_array;
        }

        if (isset($request_data->id) && !empty($request_data->id)) {
            $user_exist = User::find()->select('id, username, email, phone_no, address, status, type')->where(array('id' => $request_data->id))->one();
            if (!empty($user_exist)) {
                $response_array['statusCode'] = 200;
                $response_array['status'] = 'success';
                $response_array['responseData']['message'] = 'Profile detail!';
                $response_array['responseData']['data'] = $user_exist;
                return $response_array;
            } else {
                $response_array['statusCode'] = 500;
                $response_array['status'] = 'failure';
                $response_array['responseData']['message'] = 'User not exist!';
                return $response_array;
            }
        } else {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide valid input data!';
            return $response_array;
        }
    }

    public function actionChecklogin() {
        $response_array = array();
        $access_key = yii::$app->params['access_key'];
        $request_data = (object) $_POST;

        if (!isset($request_data)) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide input data!';
            return $response_array;
        } else if (!isset($request_data->access_key) || $request_data->access_key != $access_key) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Unauthorized Access !!';
            return $response_array;
        }

        if (isset($request_data->email) && !empty($request_data->password)) {

            $username_mail = User::find()->where(array('type' => 'user', 'email' => $request_data->email, 'status' => '1'))->count();

            if ($username_mail > 0) {

                $password_exist = User::find()->where(array('type' => 'user', 'email' => $request_data->email, 'password' => md5($request_data->password)))->count();

                if ($password_exist > 0) {
                    $res = User::find()->select('id, username, email, phone_no, address, status, type')->where(array('type' => 'user', 'email' => $request_data->email, 'password' => md5($request_data->password)))->asArray()->one();
                    $response_array['statusCode'] = 200;
                    $response_array['status'] = 'success';
                    $response_array['responseData']['message'] = 'Login Successful.';
                    $res['id'] = (int) $res['id'];
                    $response_array['responseData']['data'] = $res;
                    return $response_array;
                } else {
                    $response_array['statusCode'] = 500;
                    $response_array['status'] = 'failure';
                    $response_array['responseData']['message'] = 'Password do not match!';
                    return $response_array;
                }
            } else {
                $response_array['statusCode'] = 500;
                $response_array['status'] = 'failure';
                $response_array['responseData']['message'] = 'Email/User does not exist';
                return $response_array;
            }
        } else {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide valid input data!';
            return $response_array;
        }
    }

    public function actionAdduser() {
        $response_array = array();
        $access_key = yii::$app->params['access_key'];
        $request_data = (object) $_POST;

        if (!isset($request_data)) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide input data!';
            return $response_array;
        } else if (!isset($request_data->access_key) || $request_data->access_key != $access_key) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Unauthorized Access !!';
            return $response_array;
        }

        if (!empty($request_data->email) && !empty($request_data->phone_no)) {
            $user = new User;
            $user->type = 'user';
            $user->username = $request_data->name;
            $user->email = $request_data->email;
            //$user->password = md5($request_data->password);
            $user->phone_no = $request_data->phone_no;
            $user->address = $request_data->address;

            if ($user->save()) {
                $email_template = EmailTemplate::find()->where(array('name' => 'User_Registration'))->one();
                $this->send_email($user->email,$email_template->subject,$email_template->description);
//                $message = Yii::$app->mailer->compose()
//                        ->setFrom('ravi.chouhan@girnarsoft.com')
//                        //->setTo('nikhil.gupta@raysexperts.com')
//                        ->setTo($user->email)
//                        ->setSubject($email_template->subject)
//                        ->setHtmlBody($email_template->description)
//                        ->send();
                $response_array['statusCode'] = 200;
                $response_array['status'] = 'success';
                $response_array['responseData']['message'] = 'User Added Succefully!';
                $response_array['responseData']['data'] = $user;
                return $response_array;
            } else {
                $response_array['statusCode'] = 500;
                $response_array['status'] = 'failure';

                if (isset($user->getErrors()['email'][0]))
                    $response_array['responseData']['message'] = $user->getErrors()['email'][0];
                else
                    $response_array['responseData']['message'] = 'Failed';

                //$response_array['responseData']['data'] = $user->getErrors();
                return $response_array;
            }
        } else {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide valid input data!';
            return $response_array;
        }
    }

    public function actionForgotPassword() {
        $response_array = array();
        $access_key = yii::$app->params['access_key'];
        $request_data = (object) $_POST;
        if (!isset($request_data)) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Please provide input data!';
            return $response_array;
        } else if (!isset($request_data->access_key) || $request_data->access_key != $access_key) {
            $response_array['statusCode'] = 500;
            $response_array['status'] = 'failure';
            $response_array['responseData']['message'] = 'Unauthorized Access !!';
            return $response_array;
        }

        if (isset($request_data->email)) {
            $user_exist = User::find()->where(array('email' => $request_data->email))->count();

            if ($user_exist > 0) {
                $new_password = $this->random_password();
                $posts = Yii::$app->db->createCommand()

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\user */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-warning">
    <div class="box-body">

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true])->label('Name') ?>


<?php  if($this->title=='Create'){  ?>
    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
    <?php }  ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?php // $form->field($model, 'fullname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone_no')->textInput() ?>
    
    <?= $form->field($model, 'address')->textarea() ?>



    <?= $form->field($model, 'status')->dropDownList([ '1' => 'Active', '0' => 'Deactive', '2' => 'Approved', '3' => 'Block', '4' => 'Pending'], ['prompt' => 'Select Status']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' =>'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
    </div>
</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\SearchUser */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'fullname') ?>

    <?php // echo $form->field($model, 'phone_no') ?>

    <?php // echo $form->field($model, 'language') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_staff_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model common\models\User */
?>
<div class="box box-warning">
    <div class="box-body">

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>


    <?php  if($this->title=='Create Staff Member'){  ?>
    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
    <?php }  ?>
    <!--
    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
    -->
    <?= $form->field($model, 'fullname')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
    </div>
</div>

backend/views/user/changepassword.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\user */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Change password';
//$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
//$this->params['breadcrumbs'][] = 'Update';
?>

<div class="box box-warning">
    <div class="box-body">

        <div class="user-form">

            <?php $form = ActiveForm::begin(); ?>


            <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

            <?php if(Yii::$app->session->hasFlash('old_pa')) { ?>
                <div class="errorMessage">
                    <span style="color:red;"><?php   echo Yii::$app->session->getFlash('old_pa'); ?></span>
                </div>
            <?php } ?>


            <?= $form->field($model, 'newpassword')->passwordInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'con_password')->passwordInput(['maxlength' => true]) ?>




            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'change password' : 'change password', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

backend/views/user/create-staff.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Create Staff Member';
$this->params['breadcrumbs'][] = ['label' => 'Staff Members', 'url' => ['list-staff']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">



    <?= $this->render('_staff_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SearchUser */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-warning">
    <div class="box-body">
        <div class="user-form">

            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <p>
                <?= Html::a('Create User', ['create-user'], ['class' => 'btn btn-success']) ?>
            </p>

            <?=
            GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    //   ['class' => 'yii\grid\SerialColumn'],
                    //  'id',
                    [
                        'attribute' => 'username',
                        'label' => 'Name',
                    ],
                    // 'auth_key',
                    //   'password',
                    'email:email',
                    //'fullname',
                    'phone_no',
                    'address',
                    [
                        'attribute' => 'status',
                        'format' => 'raw',
                        'value' => function($model) {

                            switch ($model->status) {
                                case 0:
                                    return "Inactive";
                                    break;
                                case 1:
                                    return 'Active';
                                    break;
                                case 2:
                                    return "Approved";
                                    break;
                                case 3:
                                    return "Block";
                                    break;
                                case 4:
                                    return "Pending";
                                    break;
                            }                          
                        }
                    ],
                    ['class' => 'yii\grid\ActionColumn',
                        'template' => '{my_button}&nbsp;&nbsp;{view}&nbsp;&nbsp;{update}&nbsp;&nbsp;{delete}',
                        'buttons' => [
                            'my_button' => function ($url, $model, $key) {
                                return Html::a('<span class="glyphicon glyphicon-lock"></span>', ['/user/changepassword', 'id' => $model->id]);
                            },
                                ],
                            ],
                        // 'language',
                        // 'status',
                        // 'type',
                        // 'created_at',
                        // 'updated_at',
                        //  ['class' => 'yii\grid\ActionColumn'],
                        ],
                    ]);
                    ?>

        </div>
    </div>
</div>

backend/views/user/list_staff.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SearchUser */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Staff Members';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-warning">
    <div class="box-body">
        <div class="user-form">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Add Staff Member', ['create-staff'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
         //   ['class' => 'yii\grid\SerialColumn'],

          //  'id',
            'username',
           // 'auth_key',
         //   'password',
            //'email:email',
            'fullname',
           // 'phone_no',

            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function($model){

                    if($model->status=='1') {

                        return 'Active';
                    }else{

                        return 'Inactive';
                    }

                }
            ],
            ['class' => 'yii\grid\ActionColumn',
                'template' => '{my_button}&nbsp;&nbsp;{update_staff}&nbsp;{delete}',
                'buttons' => [
                    'my_button' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-lock"></span>', ['/user/changepassword', 'id' => $model->id]);
                    },
                    'update_staff' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['/user/update-staff', 'id' => $model->id]);
                    },
                ],
            ],
            // 'language',
            // 'status',
            // 'type',
            // 'created_at',
            // 'updated_at',

         //  ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>
    </div>
</div>

backend/views/user/update-staff.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update';
$this->params['breadcrumbs'][] = ['label' => 'Staff Members', 'url' => ['list-staff']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">



    <?= $this->render('_staff_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">



    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['list-users']];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="box box-warning">
    <div class="box-body">
        <div class="user-form">
            <?php
            $up = $model->status;
            switch ($up) {
                case 0:
                    $s_value = "Inactive";
                    break;
                case 1:
                    $s_value = 'Active';
                    break;
                case 2:
                    $s_value = "Approved";
                    break;
                case 3:
                    $s_value = "Block";
                    break;
                case 4:
                    $s_value = "Pending";
                    break;
            }
            ?>


            <p>
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
                <?=
                Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ])
                ?>
            </p>

            <?=
            DetailView::widget([
                'model' => $model,
                'attributes' => [
                    //     'id',
                    [
                        'attribute' => 'username',
                        'label' => 'Name',
                    ],
                    //  'auth_key',
                    //   'password',
                    'email:email',
                    //'fullname',
                    'phone_no',
                    'address',
                    //   'status',
                    [
                        'attribute' => 'status',
                        'format' => 'raw',
                        'value' => $s_value
                    ],
                //  'type',
                // 'created_at',
                // 'updated_at',
                ],
            ])
            ?>

        </div>
    </div>
</div>